spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/todo_grass
    username: root
    password: 1313
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: localhost
      port: 6379


logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: mBKO3aiV6uNZ6R96usOrSvdSGrmMwPsRaF4hT4YSdSb
