spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/todo_grass
    username: root
    password: 1313
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: localhost
      port: 6379


logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: DEBUG

jwt:
  secret: mBKO3aiV6uNZ6R96usOrSvdSGrmMwPsRaF4hT4YSdSb
  expiration-millis:
    access-token: 3600000 # 1000 * 60 * 60
    refresh-token: 86400000 # 1000 * 60 * 60 * 24

aws:
  access-key: AKIA3OMDE5J6CUA33ZV2
  secret-key: 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
  s3:
    bucket-name: todo-grass-bucket
    region: ap-northeast-2
